install sep with apt-get

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -75,7 +75,12 @@ jobs:
     - uses: actions/checkout@v2
     - name: Autobump version
       run: |
-        echo $(which sep)
+        sudo apt-get -qq update
+        sudo apt-get -qq install sed
+        export PATH="$HOME/bin:$PATH"
+
+        echo $(which sed)
+
         VERSION=$( echo $GITHUB_REF | sed 's#.*/v##' )
         PLACEHOLDER='__version__'
         VERSION_FILE='setup.py'
@@ -83,21 +88,21 @@ jobs:
         grep "$PLACEHOLDER" "$VERSION_FILE"
         sed -i "s/$PLACEHOLDER/${VERSION}/" "$VERSION_FILE"
       shell: bash
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.x'
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        python -m pip install setuptools wheel
-    - name: Build a binary wheel and a source tarball
-      run: |
-        python -m setup.py sdist wheel 
-    - name: Publish distribution to PyPi
-      uses: pypa/gh-action-pypi-publish@master
-      with:
-        password: ${{ secrets.PYPI_API_TOKEN }}
+    # - name: Set up Python
+    #   uses: actions/setup-python@v2
+    #   with:
+    #     python-version: '3.x'
+    # - name: Install dependencies
+    #   run: |
+    #     python -m pip install --upgrade pip
+    #     python -m pip install setuptools wheel
+    # - name: Build a binary wheel and a source tarball
+    #   run: |
+    #     python -m setup.py sdist wheel 
+    # - name: Publish distribution to PyPi
+    #   uses: pypa/gh-action-pypi-publish@master
+    #   with:
+    #     password: ${{ secrets.PYPI_API_TOKEN }}
 
   publish-docs:
     needs: build-n-publish
@@ -106,29 +111,35 @@ jobs:
     - uses: actions/checkout@v2    
     - name: Autobump version
       run: |
+        sudo apt-get -qq update
+        sudo apt-get -qq install sed
+        export PATH="$HOME/bin:$PATH"
+
+        echo $(which sed)
+
         VERSION=$( echo $GITHUB_REF | sed 's#.*/v##' )
         PLACEHOLDER='__version__'
         VERSION_FILE='setup.py'
         
         grep "$PLACEHOLDER" "$VERSION_FILE"
         sed -i "s/$PLACEHOLDER/${VERSION}/" "$VERSION_FILE"
-    - uses: ammaraskar/sphinx-action@master
-      with:
-        docs-folder: "docs/"
-    - name: Commit documentation changes
-      run: |
-        git clone https://github.com/EL-BID/urbanpy.git --branch gh-pages --single-branch gh-pages
-        cp -r docs/_build/html/* gh-pages/
-        cd gh-pages
-        git config --local user.email "claudio.rtega2701@gmail.com"
-        git config --local user.name "Claudio Ortega"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # the return code.
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
+    # - uses: ammaraskar/sphinx-action@master
+    #   with:
+    #     docs-folder: "docs/"
+    # - name: Commit documentation changes
+    #   run: |
+    #     git clone https://github.com/EL-BID/urbanpy.git --branch gh-pages --single-branch gh-pages
+    #     cp -r docs/_build/html/* gh-pages/
+    #     cd gh-pages
+    #     git config --local user.email "claudio.rtega2701@gmail.com"
+    #     git config --local user.name "Claudio Ortega"
+    #     git add .
+    #     git commit -m "Update documentation" -a || true
+    #     # The above command will fail if no changes were present, so we ignore
+    #     # the return code.
+    # - name: Push changes
+    #   uses: ad-m/github-push-action@master
+    #   with:
+    #     branch: gh-pages
+    #     directory: gh-pages
+    #     github_token: ${{ secrets.GITHUB_TOKEN }}
